"""Add ticket category

Revision ID: 640d6cfb86c0
Revises: 8bcaad33bbb7
Create Date: 2026-08-23 23:52:42.303290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640d6cfb86c0'
down_revision = '8bcaad33bbb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    op.execute(
        "UPDATE ticket "
        "SET category = 'Ostatní' "
        "WHERE category IS NULL "
    )

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column(
            'category',
            existing_type=sa.String(length=50),
            nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
