"""Add user roles

Revision ID: 68489d9823c1
Revises: 7a62b7db5682
Create Date: 2026-08-11 17:22:51.133623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68489d9823c1'
down_revision = '7a62b7db5682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    op.execute(
        "UPDATE user "
        "SET role = 'user' "
        "WHERE role is NULL"
    )

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column(
            'role',
            existing_type=sa.String(length=20),
            nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
