"""Add ticket resolved date

Revision ID: 821fb7adaf2a
Revises: 640d6cfb86c0
Create Date: 2026-08-29 00:53:01.599549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821fb7adaf2a'
down_revision = '640d6cfb86c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('resolved_at')

    # ### end Alembic commands ###
