"""Add ticket assignment

Revision ID: d41f4a2f150b
Revises: 68489d9823c1
Create Date: 2026-08-11 18:34:53.501191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd41f4a2f150b'
down_revision = '68489d9823c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_ticket_assigned_user_id', 'user', ['assigned_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ticket_assigned_user_id', type_='foreignkey')
        batch_op.drop_column('assigned_user_id')

    # ### end Alembic commands ###
